#!/usr/bin/env bash
# Story from /etc/passwd

while IFS=: read -r username password userid groupid gecos home shell; do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $gecos"
    echo
done < /etc/passwd

