#!/usr/bin/env bash
# Generate a story for each user in /etc/passwd

while IFS=: read -r username password userid groupid desc home shell; do
    echo "The user $username is part of the $groupid gang, lives in $home and rides $shell."
    echo "USER ID's place is protected by the passcode $password, more info about the user here: $desc"
    echo
done < /etc/passwd

