#!/usr/bin/env bash
# Check information about the school file

if [ -e school ]; then
    echo "school file exists"

    # Check if the file is empty
    if [ ! -s school ]; then
        echo "school file is empty"
    else
        echo "school file is not empty"
    fi

    # Check if the file is a regular file
    if [ -f school ]; then
        echo "school is a regular file"
    fi
else
    echo "school file does not exist"
fi

