#!/usr/bin/env bash
#.
PID_FILE="/tmp/myscript.pid"
echo $$ > "$PID_FILE"
trap 'echo "I hate the kill command"' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f "$PID_FILE"; exit' SIGQUIT SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
