#!/usr/bin/env bash
#.

PID_FILE=" /var/run/myscript.pid"
echo $$ > "$PID_FILE"

trap 'echo "I hate the kill command"; rm -f "$PID_FILE"; exit' SIGTERM SIGQUIT
trap 'echo "Y U no love me?!"' SIGINT

while true; do
    echo "To infinity and beyond"
    sleep 1
done
