#!/usr/bin/env bash
# Manages 'manage_my_process'

PIDFILE="/var/run/my_process.pid"

case "$1" in
    start)
        ./manage_my_process &
        echo $! > "$PIDFILE"
        echo "manage_my_process started"
        ;;
    
    stop)
        kill "$(cat "$PIDFILE")"
        sudo bash -c rm -f "$PIDFILE"
        echo "manage_my_process stopped"
        ;;
    
    restart)
        kill "$(cat "$PIDFILE")"
        rm -f "$PIDFILE"
        ./manage_my_process &
        echo $! > "$PIDFILE"
        echo "manage_my_process restarted"
        ;;
    
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        ;;
esac
